decoded_columns = [
    'Checking_Account_Status',
    'Duration_Months',
    'Credit_History',
    'Purpose',
    'Credit_Amount',
    'Savings_Account',
    'Employment_Since',
    'Installment_Rate',
    'Personal_Status_Sex',
    'Other_Debtors_Guarantors',
    'Residence_Since',
    'Property',
    'Age_Years',
    'Other_Installment_Plans',
    'Housing',
    'Number_Credits',
    'Job',
    'Number_Liable_People',
    'Telephone',
    'Foreign_Worker'
]

code_mapping = {
    'A11': 'smaller 0 DM',
    'A12': 'smaller 200 DM',
    'A13': 'greater_equal 200 DM',
    'A14': 'no checking account',
    'A30': 'no credits taken/ all credits paid back duly',
    'A31': 'all credits at this bank paid back duly',
    'A32': 'existing credits paid back duly till now',
    'A33': 'delay in paying off in the past',
    'A34': 'critical account/other credits existing (not at this bank)',
    'A40': 'car (new)',
    'A41': 'car (used)',
    'A42': 'furniture/equipment',
    'A43': 'radio/television',
    'A44': 'domestic appliances',
    'A45': 'repairs',
    'A46': 'education',
    'A48': 'retraining',
    'A49': 'business',
    'A410': 'others',
    'A61': 'smaller 100 DM',
    'A62': 'smaller 500 DM',
    'A63': 'smaller 1000 DM',
    'A64': 'greater_equal 1000 DM',
    'A65': 'unknown/no savings account',
    'A71': 'unemployed',
    'A72': 'smaller 1 year',
    'A73': 'smaller 4 years',
    'A74': 'smaller 7 years',
    'A75': 'greater_equal 7 years',
    'A91': 'male : divorced/separated',
    'A92': 'female : divorced/separated/married',
    'A93': 'male : single',
    'A94': 'male : married/widowed',
    'A95': 'female : single',
    'A101': 'none',
    'A102': 'co-applicant',
    'A103': 'guarantor',
    'A121': 'real estate',
    'A122': 'if not A121 : building society savings agreement/ life insurance',
    'A123': 'if not A121/A122 : car or other, not in attribute 6',
    'A124': 'unknown/no property',
    'A141': 'bank',
    'A142': 'stores',
    'A143': 'none',
    'A151': 'rent',
    'A152': 'own',
    'A153': 'for free',
    'A171': 'unemployed/unskilled - non-resident',
    'A172': 'unskilled - resident',
    'A173': 'skilled employee / official',
    'A174': 'management/ self-employed/ highly qualified employee/ officer',
    'A191': 'none',
    'A192': 'yes, registered under the customers name',
    'A201': 'yes',
    'A202': 'no'
}